services:
  postgres:
    image: postgres:15
    container_name: momoyu_postgres
    environment:
      POSTGRES_DB: momoyu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - momoyu_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: momoyu_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - momoyu_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: momoyu_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/momoyu
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - momoyu_network
    volumes:
      - ./backend:/app
    restart: unless-stopped
    profiles:
      - production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: momoyu_frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://backend:8000
    depends_on:
      - backend
    networks:
      - momoyu_network
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  momoyu_network:
    driver: bridge